# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scane_1.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1338, 768)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setWindowTitle("MainWindow")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.BG = QtWidgets.QLabel(self.centralwidget)
        self.BG.setEnabled(True)
        self.BG.setGeometry(QtCore.QRect(0, 0, 1366, 768))
        self.BG.setText("")
        self.BG.setPixmap(QtGui.QPixmap("BG_1.png"))
        self.BG.setScaledContents(True)
        self.BG.setOpenExternalLinks(False)
        self.BG.setObjectName("BG")
        self.hari = QtWidgets.QLabel(self.centralwidget)
        self.hari.setGeometry(QtCore.QRect(1050, 20, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hari.setFont(font)
        self.hari.setObjectName("hari")
        self.koma = QtWidgets.QLabel(self.centralwidget)
        self.koma.setGeometry(QtCore.QRect(1110, 20, 25, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.koma.setFont(font)
        self.koma.setObjectName("koma")
        self.tanggal = QtWidgets.QLabel(self.centralwidget)
        self.tanggal.setGeometry(QtCore.QRect(1120, 20, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tanggal.setFont(font)
        self.tanggal.setObjectName("tanggal")
        self.strip = QtWidgets.QLabel(self.centralwidget)
        self.strip.setGeometry(QtCore.QRect(1150, 20, 10, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.strip.setFont(font)
        self.strip.setObjectName("strip")
        self.bulan = QtWidgets.QLabel(self.centralwidget)
        self.bulan.setGeometry(QtCore.QRect(1160, 20, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bulan.setFont(font)
        self.bulan.setObjectName("bulan")
        self.strip_2 = QtWidgets.QLabel(self.centralwidget)
        self.strip_2.setGeometry(QtCore.QRect(1190, 20, 10, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.strip_2.setFont(font)
        self.strip_2.setObjectName("strip_2")
        self.tahun = QtWidgets.QLabel(self.centralwidget)
        self.tahun.setGeometry(QtCore.QRect(1200, 20, 61, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tahun.setFont(font)
        self.tahun.setObjectName("tahun")
        self.strip_3 = QtWidgets.QLabel(self.centralwidget)
        self.strip_3.setEnabled(True)
        self.strip_3.setGeometry(QtCore.QRect(1248, 10, 10, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.strip_3.setFont(font)
        self.strip_3.setObjectName("strip_3")
        self.jam = QtWidgets.QLabel(self.centralwidget)
        self.jam.setGeometry(QtCore.QRect(1260, 20, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.jam.setFont(font)
        self.jam.setObjectName("jam")
        self.titik2 = QtWidgets.QLabel(self.centralwidget)
        self.titik2.setGeometry(QtCore.QRect(1285, 20, 20, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titik2.setFont(font)
        self.titik2.setObjectName("titik2")
        self.menit = QtWidgets.QLabel(self.centralwidget)
        self.menit.setGeometry(QtCore.QRect(1295, 20, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menit.setFont(font)
        self.menit.setObjectName("menit")
        self.tekanan = QtWidgets.QLabel(self.centralwidget)
        self.tekanan.setGeometry(QtCore.QRect(1060, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.tekanan.setFont(font)
        self.tekanan.setObjectName("tekanan")
        self.bar = QtWidgets.QLabel(self.centralwidget)
        self.bar.setGeometry(QtCore.QRect(1140, 60, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.bar.setFont(font)
        self.bar.setObjectName("bar")
        self.derajat = QtWidgets.QLabel(self.centralwidget)
        self.derajat.setGeometry(QtCore.QRect(1220, 60, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.derajat.setFont(font)
        self.derajat.setObjectName("derajat")
        self.o_derajat = QtWidgets.QLabel(self.centralwidget)
        self.o_derajat.setGeometry(QtCore.QRect(1265, 50, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.o_derajat.setFont(font)
        self.o_derajat.setObjectName("o_derajat")
        self.celcius = QtWidgets.QLabel(self.centralwidget)
        self.celcius.setGeometry(QtCore.QRect(1280, 60, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.celcius.setFont(font)
        self.celcius.setObjectName("celcius")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.hari.setText(_translate("MainWindow", "Jumat"))
        self.koma.setText(_translate("MainWindow", ","))
        self.tanggal.setText(_translate("MainWindow", "17"))
        self.strip.setText(_translate("MainWindow", "-"))
        self.bulan.setText(_translate("MainWindow", "12"))
        self.strip_2.setText(_translate("MainWindow", "-"))
        self.tahun.setText(_translate("MainWindow", "2020"))
        self.strip_3.setText(_translate("MainWindow", "|"))
        self.jam.setText(_translate("MainWindow", "24"))
        self.titik2.setText(_translate("MainWindow", ":"))
        self.menit.setText(_translate("MainWindow", "59"))
        self.tekanan.setText(_translate("MainWindow", "0.29"))
        self.bar.setText(_translate("MainWindow", "bar"))
        self.derajat.setText(_translate("MainWindow", "20"))
        self.o_derajat.setText(_translate("MainWindow", "o"))
        self.celcius.setText(_translate("MainWindow", "C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
